### ISSUE TITLE
could not find in maven center by package name io.ebean

### ISSUE THREAD

**Issue by dreamkidd** [ebean-orm/ebean-spring#13]
could not find in maven center by package name io.ebean
could change to the io.ebean on maven center

**Comment by rbygrave** [comment]
That is correct, I'll be looking to release some ebean spring artifacts shortly (ebean-spring-txn).  This has had some discussion on the google group: https://groups.google.com/forum/#!forum/ebean

Note that the google group is the place to ask questions.  We generally want to leave the github issues for commit related changes (bugs, enhancements, refactoring).

Thanks, Rob.

**Comment by rbygrave** [comment]
ebean-spring-txn 10.1.1 released
