### ISSUE TITLE
Spring Boot EBean with HikariCP

### ISSUE THREAD

**Issue by javajack** [ebean-orm/ebean-spring#7]
I want to leverage the EBean with Spring Boot and Spring Transactions.

I already create DataSource from HikariCP. I want to leverage that datasource instance and want to feed that instance to Ebean.

So what is the approach to achieve this ?

**Comment by rbygrave** [comment]
The example at: https://github.com/ebean-orm-examples/example-springboot

This example has been just updated to do this.

Note that there are downsides to Spring transactions (more complexity and
less functionality) relative to Ebean's @Transactional ... and similarly I
need to document the pros/cons of Ebean's own DataSource implementation.

**Comment by rbygrave** [comment]
May as well close this issue.
