### ISSUE TITLE
Logging dependencies

### ISSUE THREAD

**Issue by ksperling** [ebean-orm/ebean-spring#9]
It seems somewhat strange that the `spring-ebean` code itself uses JUL, but also pulls in a dependency on `jcl-over-slf4j`.

I would propose that
* `ebean-spring` itself should use slf4j just like ebean
* leave it up to the user to deal with Spring's own JCL dependency

Let me know if this approach sounds OK to you and I'll submit a PR.

**Comment by rbygrave** [comment]
What you suggest is exactly correct.  ebean-spring should only using slf4j (like Ebean).

**Comment by rbygrave** [comment]
Fixed with the linked merge request, closing.
